### ISSUE TITLE
Refactor db.session.flush() is get_issues to reduce confusion

### ISSUE THREAD

**Issue by pmackay** [codeforamerica/cfapi#135]
When I spent some time trying to get it working with SQLite, I found that problems with the definition of earlier projects were causing an error in the call to `db.session.flush()` at the start of `get_issues()`. It would be better to flush the stuff from earlier functions at the end of those functions rather than as a side effect of `get_issues()`.

This could of course be something to consider in the v2 refactor.

**Comment by ondrae** [comment]
We found one place were things aren't saved yet when they hit the flush() in get_issues().

When a new story [is added](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L695) it doesn't get a distinct commit or flush itself.

- [ ] Add a flush to the save_story_info() function.
- [ ] Find other non saved objects making it into get_issues

**Comment by migurski** [comment]
`:robot:` KILL SQLALCHEMY `:robot:`
