### ISSUE TITLE
Use repo name when no project name given

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#168]
#### Description
None of the Data.gov projects have names in the CfAPI.
![screen shot 2015-01-07 at 12 16 27 pm](https://cloud.githubusercontent.com/assets/595778/5652634/096ee14a-9667-11e4-8163-6665e7d311fa.png)

They give us a [list of projects is given](https://docs.google.com/spreadsheet/pub?key=0ArHmv-6U1drqdG81Tjh5RjlBTkR3RVdGREFZdDluZ2c&output=csv), with no project names. 

We are supposed to use the repo name from Github in its place, but its not happening. Its for all of their projects, yet the [Data.gov site](http://codeforamerica.org/api/projects/2461) is the most prolific because of all the open issues.

**Comment by tmaybe** [comment]
Could not reproduce, but I wrote a test verifying that missing project names are replaced with github repo names.
