### ISSUE TITLE
Org Issues endpoint no longer working

### ISSUE THREAD

**Issue by CristinaSolana** [codeforamerica/cfapi#173]
I'm wondering is the org issues endpoint was deprecated, it was working until a few days ago and now returns an empty object, examples: http://codeforamerica.org/api/organizations/Code-for-San-Francisco/issues of http://codeforamerica.org/api/organizations/Code-for-Miami/issues

**Comment by ondrae** [comment]
Hey @CristinaSolana it was a rare bug that affected a few Brigades. Our best guess is that we got throttled by GitHub at an inopportune time in the hourly update, which set some issues with an updated flag, yet the content got deleted. We're digging into it more. Thanks for the heads up.

**Comment by CristinaSolana** [comment]
@ondrae, impressively fast. Thank you! :)
