### ISSUE TITLE
Compress the JSON output

### ISSUE THREAD

**Issue by volkanunsal** [codeforamerica/cfapi#202]
The JSON output is not large, but it takes 1000ms to send it down the wire. My guess is this is probably because it's not compressed. If there is a quick way of minifying the JSON output in Python, perhaps it can be turned on.

**Comment by migurski** [comment]
We’re proxying everything through Apache, so we can probably turn on [`mod_deflate`](http://httpd.apache.org/docs/2.2/mod/mod_deflate.html) instead of messing with the content.

**Comment by migurski** [comment]
…turned it on. Did it help?

**Comment by volkanunsal** [comment]
Yes, content download time is down to 300ms. But the time to first bye (TTFB) is still around 800ms.  


![screen shot 2015-03-11 at 2 32 49 am](https://cloud.githubusercontent.com/assets/151600/6591483/12235eae-c797-11e4-8ed4-05d973b326cd.png)

**Comment by migurski** [comment]
Some of that might be a Heroku-is-slow thing. Or a database-is-slow thing.
