### ISSUE TITLE
poll github projects and analyze contents for status information

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/cfapi#204]
- [x] Poll github projects that the API knows about. For projects that have a _civic.json_ file at root level, check to see if they have a _status_ field.
- [x] If the _status_ field exists, determine whether it's implemented consistently across all projects.
- [x] Either way, choose a standard method of representing a project's status in a civic.json file that the API will understand.

This is a component of issue #133

**Comment by ondrae** [comment]
I'm getting closer to needing to knowing what is out there. I'm looking to create a recommended list of statuses.

**Comment by tmaybe** [comment]
The API knows about 27 projects (hosted on GitHub) that have civic.json files. Here are links to them all:

https://raw.githubusercontent.com/rasmi/my-neighborhood/master/civic.json
https://raw.githubusercontent.com/BetaNYC/civic.json/master/civic.json
https://raw.githubusercontent.com/ameensol/dataExplorer/master/civic.json
https://raw.githubusercontent.com/ameensol/dataExplorerAPI/master/civic.json
https://raw.githubusercontent.com/BetaNYC/betanyc-support-ribbon-css/master/civic.json
https://raw.githubusercontent.com/BetaNYC/NY-Waterways-GTFS-data/master/civic.json
https://raw.githubusercontent.com/rasmi/homeless-nyc/master/civic.json
https://raw.githubusercontent.com/MTA-Service-Alerts-beta-nyc/service-alerts/master/civic.json
https://raw.githubusercontent.com/seanluciotolentino/dangerous-intersections/master/civic.json
https://raw.githubusercontent.com/clhenrick/am-i-rent-stabilized/master/civic.json
https://raw.githubusercontent.com/josselinphilippe/bagitnyc/master/civic.json
https://raw.githubusercontent.com/hondacivicapps/hondacivicapps.github.io/master/civic.json
https://raw.githubusercontent.com/codefordc/guides/master/civic.json
https://raw.githubusercontent.com/DangerousRDNYC/DangerousRDNYC/master/civic.json
https://raw.githubusercontent.com/Emrals/Emrals-Android/master/civic.json
https://raw.githubusercontent.com/codefordc/dc-campaign-finance-watch/master/civic.json
https://raw.githubusercontent.com/rasmi/crime-nyc/master/civic.json
https://raw.githubusercontent.com/codefordc/open211/master/civic.json
https://raw.githubusercontent.com/codefordc/ancfinder/master/civic.json
https://raw.githubusercontent.com/codefordc/codefordc-2.0/master/civic.json
https://raw.githubusercontent.com/codefordc/districthousing/master/civic.json
https://raw.githubusercontent.com/childcaremap/NYCdaycare/master/civic.json
https://raw.githubusercontent.com/NYPDVisionZeroAccountability/compstat-vs-moving-violation-enforcement/master/civic.json
https://raw.githubusercontent.com/BetaNYC/Bike-Share-Data-Best-Practices/master/civic.json
https://raw.githubusercontent.com/BetaNYC/budgetBuddy/master/civic.json
https://raw.githubusercontent.com/talos/acris-bigquery/master/civic.json
https://raw.githubusercontent.com/camsys/onebusaway-nyc-atstop/master/civic.json

**Comment by ondrae** [comment]
I wrote a quick script to track civic.json usage in the wild.

```
Number of time a key was used.
{
    "bornAt": 21,
    "categories": 26,
    "communityPartner": 4,
    "conformsTo": 3,
    "contact": 4,
    "data": 1,
    "geography": 27,
    "governmentPartner": 4,
    "moreInfo": 4,
    "name": 3,
    "needs": 25,
    "politicalEntity": 19,
    "status": 27,
    "thumbnailUrl": 25,
    "type": 26,
    "video": 1
}

The interesting bits of the values for each key
{
    "bornAt": [
        "Code for Good",
        "Reinvent 311",
        "#codeacross",
        "BetaNYC hacknight",
        "Parsons, The New School For Design",
        "New School",
        "CodeAcross NYC",
        "Code for DC",
        "BetaNYC Maillist",
        "BetaNYC CodeAcrossNYC",
        "PennApps",
        "CodeAcross New York NY",
        "BetaNYC Citibike Hacknights",
        "CityCamp"
    ],
    "categories": [
      # I cleaned it up a litte
         "Community" 5
            "Open Data" 9
             "Politics" 2
             "Transparency" 3
            "Transportation" 4
            "Housing" 7
           "Environment" 3
           "Financial" 4
           "Law Enforcement" 3
        ]
    ],
    "communityPartner": [
     "http://www.breadforthecity.org/"
    ],
    "conformsTo": [
        "http://codefordc.org/resources/specification.html"
    ],
    "contact": [
        {
            "email": "contactus@ancfinder.org",
            "name": "",
            "twitter": "@ancfinder"
       }
    ],
    "data": [
        {
            "ANC Commissioners": "http://ancfinder.org/static/ancs.json",
            "ANC Meetings": "http://ancfinder.org/static/meetings.json"
        }
    ],
    
    "needs": [
      "AngularJS Dev"
          "d3.js Dev"
            "JS Dev"
           "Node Dev"
           "UX Designer"
            "Data Wrangler"
            "Android Dev"
           "Natural Language Processor"
            "Database experts"
           "Mappers"
            "Web developer"
           "Data scientist"
          "Web Hosting"
            "Promotion"
           "User Testing"
            ...
    ],
    "status": [
        "Beta",
        "In Development",
        "Complete",
        "In Progress",
        "Production",
        "Discovery",
        "Alpha",
        "Ideation"
    ],
    "thumbnailUrl": [
        "http://upload.wikimedia.org/wikipedia/commons/d/d0/Msgpack-json_copy.png",
        "http://upload.wikimedia.org/wikipedia/commons/a/a3/United_States_Capitol_west_front_edit2.jpg",
        "http://inhabitat.com/nyc/wp-content/blogs.dir/2/files/2011/10/EastRiverFerry1-537x357.jpg",
        "https://raw.github.com/rasmi/homeless-nyc/master/ic_launcher-web.png",
      ...
    ],
    "type": [
        "Web App",
        "Chrome Extension",
        "API",
        "Dataset",
        "Android App",
        ...
    ],
    "video": [
        "https://www.youtube.com/watch?v=cAUGp_nvUZA&feature=youtu.be"
    ]
} 
```
