### ISSUE TITLE
return a specific organization's issues in random order

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/cfapi#216]
On the `/api/organizations/<organization_name>/issues` endpoint, issues are currently returned by most recently added. We want them to return in random order, the way the `/api/issues` endpoint does. See codeforamerica/civic-issue-finder#29.

#### Files
app.py

#### Tasks
- [x] add a `.order_by(func.random())` to the end of [the issue query](https://github.com/codeforamerica/cfapi/blob/master/app.py#L842) in get_orgs_issues()
- [x] write tests to verify random-ordered issues returned from both endpoints

**Comment by tmaybe** [comment]
@ondrae @migurski apparently issues have always been returned from this particular endpoint ordered by most recently added. Is changing this to random a breaking change for the API?

Would it make more sense to add support for something like a `sort_by=random` parameter that the civic issue finder could take advantage of?

**Comment by tmaybe** [comment]
See also: Issue paging is pointless because of randomization #167

**Comment by ondrae** [comment]
The most common use of a Brigade specific request for issues is by the issue finder, like on http://codeforsanfrancisco.org/. Refresh it a few times and see that it always returns in the same way. We got [a request](https://github.com/codeforamerica/civic-issue-finder/issues/29) to fix it.

Adding a search parameters, like suggested in #167 will be best. I still think random as the default, at least by the issue finder, is most useful.

**Comment by tmaybe** [comment]
I have no objection to making the change if we all agree it doesn't require a bump to [*CfAPI Corgi*](https://github.com/codeforamerica/cfapi/issues/130#issuecomment-55342120)

**Comment by tmaybe** [comment]
I made the required changes and submitted pull request #217, take a look.
