### ISSUE TITLE
Cannot install requirements with no postgres installation

### ISSUE THREAD

**Issue by Jeff-Meadows** [codeforamerica/cfapi#225]
I was trying to follow the directions in `README.md` but `pip install -r requirements.txt` fails during pip install of `psycopg2` with `Error: pg_config executable not found.`

The readme seems to indicate that development can proceed with sqlite, thus skipping the postgres installation, but this is apparently out of date.

Interestingly enough, the psycopg2 package doesn't seem to be used; removing it from requirements.txt allowed me to install the rest of the requirements. I think sqlite compatibility is being tracked in #128 - and the current status seems to be that it is not (for example, a99a4d1f971d1f79f40319d09559a6b1e678f063 introduced reliance on `tsvector`, a postgres-only type).

If sqlite isn't supported (and postgres required), it should be clear from the README.

**Comment by ondrae** [comment]
Hey @Jeff-Meadows thanks for pointing this out. We were trying to support sqlite back when, yet we decided to go Postgres only.

I've cleared up any [ambiguity in the README](https://github.com/codeforamerica/cfapi/blob/master/README.md#development-setup).

psycopg2 is required by SQLAlchemy if it wants to talk to postgres. I did catch a few other libraries that we didn't need anymore though.
