### ISSUE TITLE
Widget on Data.gov down

### ISSUE THREAD

**Issue by eddietejeda** [codeforamerica/cfapi#230]
I was looking at [Data.gov](http://www.data.gov/developers/open-source) and saw this error:

![screen shot 2015-06-18 at 2 18 22 pm](https://cloud.githubusercontent.com/assets/669988/8242539/f305c8a0-15c4-11e5-960d-e7c31d820a34.png)

When you open up the iframe that generates this message, it points to [here](https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Data.gov&labels=help wanted&number=30) and seems to work (sometimes) when you load it directly. On Data.gov it never loads.

**Comment by migurski** [comment]
This is the result of a timeout, so I’m guessing that the underlying CfAPI database queries are timing out. cc @ondrae.

**Comment by eddietejeda** [comment]
Ya'll use New Relic?

**Comment by ondrae** [comment]
Actual app timeouts only happen after 30 seconds. We've set an artificial timeout of 5 seconds. Looking at the past week of data on New Relic, the function [get_orgs_issues](https://github.com/codeforamerica/cfapi/blob/master/app.py#L830) is taking an average of 14s. This is mostly some large spikes on certain queries.

I think this is kind of unique to Data.gov, in that they have the most open issues of any group on the cfapi with 259 open issues, where Code for San Francisco never ever times out and only has 51 issues.

Speeding up that query should help.

**Comment by migurski** [comment]
FWIW, I would expect this kind of query to take double-digit numbers of milliseconds. So, query optimization and indexing time!

**Comment by eddietejeda** [comment]
Indeed.

And [memcache](https://elements.heroku.com/addons/memcachier#addon-plans). The Heroku Memcachier add-on gives 25MB of free storage. With that you can cache all responses.

**Comment by migurski** [comment]
The results are randomized on each request, so memcache would potentially be improper.

**Comment by ondrae** [comment]
Data.gov is probably using too big of a query anyways. `https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Data.gov&labels=help wanted&number=30`
That `number=30` means to show off 30 random issues. All of our other instances show off 3 or 6 random issues.

That said, when I shorten it to just 3, https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Data.gov&labels=help wanted&number=3, it still usually fails.

**Comment by migurski** [comment]
Yeah, 30 is not a big number. It’s hard to tell from the code in `get_orgs_issues()`, but I would guess that it’s pulling a very large number of issues from the database and filtering them client-side? First step to fixing this is to inspect what’s actually being sent to Postgres.

**Comment by migurski** [comment]
I’m doing a little digging, asking for 1, 2, and 3 issues from the API e.g. `http://www.codeforamerica.org/api/issues?per_page=3`. Each request is generating an outrageously large number of queries to the database backend, mostly this one:

```
SELECT label.id AS label_id, label.name AS label_name, label.color AS label_color, label.url AS label_url, label.issue_id AS label_issue_id 
FROM label 
WHERE %(param_1)s = label.issue_id
```

I’m seeing 493 individual SELECT queries like that in the `per_page=3` case, and 356 in the `per_page=2` case.

**Comment by ondrae** [comment]
The query the cfapi is receiving is `/api/organizations/Data.gov/issues/labels/help%20wanted?per_page=30`

The relevant code is at https://github.com/codeforamerica/cfapi/blob/master/app.py#L829

The problem comes with the sql. `SELECT label.id AS label_id, label.name AS label_name, label.color AS label_color, label.url AS label_url, label.issue_id AS label_issue_id FROM label WHERE %(param_1)s = label.issue_id` is being called 735 times on that data.gov query ...

**Comment by ondrae** [comment]
I've upped the timeout to be 10 seconds. https://github.com/codeforamerica/civic-issue-finder/commit/80bcf89e988e7e046422bdbac167d5a6240233e4

This is a bandaid until we can refactor [get_issues_by_label](https://github.com/codeforamerica/cfapi/blob/master/app.py#L1170)

**Comment by ondrae** [comment]
SO FAST NOW!!! Good work @tmaybe 
http://tools.pingdom.com/fpt/#!/exK0aH/http://www.data.gov/developers/open-source
