### ISSUE TITLE
Trailing slash on github links fail 

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#235]
#### Description
Need to add support for trailing slashes on links to Github projects.

Code for San Francisco uses [a spreadsheet](https://docs.google.com/spreadsheets/d/1iijLe3aS_l4Hn8YEblfi_ZRU2expkuB-uS7V0NVQp2w/edit#gid=0) as the source for their projects. 

One of their projects was entered with a trailing slash. https://github.com//thfield/sf-map/
When the cfapi tries to ask the github api about that project, it fails. https://api.github.com/repos/thfield/sf-map/
Remove the trailing slash and the api call works. https://api.github.com/repos/thfield/sf-map

#### To Fix
Add support for trailing slashes in project links, especially when converting to the gihub api url.
Most likely in this line https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L345

**Comment by tmaybe** [comment]
closed by #254
