### ISSUE TITLE
Meetup RSVP's included with attendance

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#241]
#### Description
We've built some tools to help track attendance at your hack nights.
![screen shot 2015-07-31 at 1 44 55 pm](https://cloud.githubusercontent.com/assets/595778/9318151/d15b2e06-44f5-11e5-834d-398c3289f362.png)

You can have people checkin at:
http://www.codeforamerica.org/brigade/checkin/
http://www.codeforamerica.org/brigade/Open-Twin-Cities/checkin?event=Hack+Night&question=How+did+you+hear+about+us?

Recently @wbushey did some great work to add in Meetup RSVPs to this attendance data. I think this is great, as it is a historical sense of how many people are going to your events. Unfortunately you can't get emails out of Meetup, so we still encourage you to use our /checkin tool or build your own.

#### Question
Does adding in RSVPs to attendance mess with how you would use this data?

**Comment by roughani** [comment]
FWIW, Meetup RSVPs are pretty unreliable. They're good for comparing the level of interest across different hack nights, but the number of people who RSVP is almost always different from the number of peeps that show up. And we cross-post events in our hacker space's Meetup group, too.

**Comment by vykster** [comment]
We have volunteers manually checking in everyone at the door. We also cap attendance b/c of venue size, we are looking at adding a "waiting list" feature to the event tool we are using so that we can figure out how best to grow.

In the short term we won't be using this check-in tool as we've gotten used to a larger feature set. However - as we have the capacity we will intergrate with this tool via API or work with CfA to add the features we use.

**Comment by ondrae** [comment]
@roughani Exactly. I tried going down the [rabbit hole](https://github.com/codeforamerica/cfapi/issues/239#issuecomment-130787460) of getting attendance from the Meetup API. Its not going to happen.

I guess I need to remove the Meetup code and data, and again only report actual attendance.

What about adding an `/events/rsvps` attribute to the CfAPI? I just dug into the Meetup docs some more and it looks like we can get RSVPs for all events, not just ones that I am a co-organizer for. I think thats what I'll do.

**Comment by ondrae** [comment]
@vykster oh for sure use your own tools. If possible, I'd like to connect yours to ours, just so we have good and accurate data from across the movement. No rush though.

**Comment by vykster** [comment]
@ondrae Yes! I just imagine it'll be a few more months before we have the bandwidth to work on connecting. 

What would be your thoughts around an upload CSV tool? I could then ask volunteers to upload data from current and past events. Many of our volunteers and organizers aren't programmers.

**Comment by ondrae** [comment]
I'm going to pull out all the Meetup code and data into a separate endpoint. https://github.com/codeforamerica/cfapi/issues/243

**Comment by ondrae** [comment]
@vykster Yeah lets talk about it. I could help build it. Just want to know a little more about the tools you are already using. I'll ping you in a different thread.

**Comment by zmon** [comment]
In KC we have a sign in sheet.  When I have time I enter it into a google spread sheet (that has not happened in some time).  The accuracy of the sign in sheet fluctuates, but is much better than what meetup has.  It would be nice to have an app that would check people in, but that would require a dedicated laptop which is a barrier for us.
