### ISSUE TITLE
Add Code for Charlotte to cfapi

### ISSUE THREAD

**Issue by RowdyChildren** [codeforamerica/cfapi#246]
How can we add Code for Charlotte to the cfapi? I updated our information in the Google Sheet. But we are not listed in the cfapi.<br>
Our projects url is a csv at http://www.codeforcharlotte.org/projects.csv <br>
Our updates url is an rss feed at http://www.codeforcharlotte.org/project-updates?format=rss <br>
Our meetup is http://www.meetup.com/Code-For-Charlotte/

**Comment by RowdyChildren** [comment]
never mind we are listed...I think it just takes time to update

**Comment by ondrae** [comment]
Yeah it updates every hour. Looks good though, http://www.codeforamerica.org/brigade/Code-for-Charlotte/
