### ISSUE TITLE
"Code for Philly" not appearing in Brigades

### ISSUE THREAD

**Issue by varNinja** [codeforamerica/cfapi#261]
The Philadelphia brigade (Code for Philly) isn't on the Organizations list on the API (https://www.codeforamerica.org/api/organizations.geojson) and it doesn't appear on the Brigade website, but it does appear on the Brigade Info Google doc (https://docs.google.com/spreadsheets/d/1cFswd6i-80f7rMKJzLOcJzr1Zb7gUukPkoi_I9MAdjQ)

**Comment by ondrae** [comment]
I pull your list of projects from codeforphilly.org/projects.csv. It looks like the link to https://github.com/yadaguru/yadaguru-app/issues is breaking my update process. I never thought someone would use the /issues link as their main project link. I'll need to add support for that asap.

Until then, think you could drop the /issues from that link? Code for Philly should show back up then.

**Comment by ondrae** [comment]
#### Description
Add support for a github /issues link to be the main project link. We wont treat this link any different from any other github link.

#### Files
run_update.py

#### To Fix
- [ ] In [update_project_info](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L391), after checking for github link or not, check for /issues in the url and drop it.
- [ ] Write a test to ensure it works

**Comment by bennovack** [comment]
I've dropped /issues from the link as a near-term fix.

**Comment by ondrae** [comment]
Y'all are back on the list now. http://www.codeforamerica.org/brigade/Code-for-Philly/

I'll work on that bug asap though.
