### ISSUE TITLE
.env is not processed

### ISSUE THREAD

**Issue by milovanderlinden** [codeforamerica/cfapi#313]
I followed the instruction in the readme to set up a development environment. I add `print(os.environ.get('DATABASE_URL'))` to see that the output is `None` but my database url is in the .env file. Is python-dotenv missing? Or are you parsing .env internally?

**Comment by tdooner** [comment]
Hi @milovanderlinden, in its current state, this is a documented behavior. The README instructs to start the server with:

```
env `cat .env` python app.py runserver
```

We probably _should_ add dotenv to do this automatically, but for now I'm going to close this issue.
