### ISSUE TITLE
Code-for-the-Netherlands vs Code-for-NL

### ISSUE THREAD

**Issue by milovanderlinden** [codeforamerica/cfapi#314]
Code-for-the-Netherlands (as chapter id) has been replaced by Code-For-NL by @jgroenen. And now both show up in http://api.codeforamerica.org/api/organizations.geojson

Please advice if the two should be merged first or if one of them needs to be deleted from the database and if so, which one.

**Comment by tdooner** [comment]
Hi @milovanderlinden, my course of action to fix this will be to delete "Code-for-the-Netherlands", as I assumed @jgroenen was from there and was somewhat authoritative on its name.

Sorry if this is causing any bugs on your end -- if I may ask, what is your usage of the CfAPI? As its current maintainer, knowing how people are using it will help me to not break your use-cases going forward.

**Comment by milovanderlinden** [comment]
Hi @tdooner I can work with your fix. please let me know when it is implemented, so I can alter my code to match.

I am working on the codeforall website. Work in progress here: http://www.codefor.nl/codeforall.org/ it uses the cfapi to pull in organization and projects information for the code for all chapters and projects. It then mixes the information with standard pages and posts. Currently I am pulling the json files with a small batch script because of the ssl certificate issue, but in a later stage I can always revert this to have a live connection.

**Comment by tdooner** [comment]
Cool, thanks. I deleted the extra record yesterday. Now I'm seeing only one record form the Netherlands. Let me know if you need anything else!
