### ISSUE TITLE
Enhance api hierarchy

### ISSUE THREAD

**Issue by milovanderlinden** [codeforamerica/cfapi#332]
Currently, Code For All is implemented at the level of brigades. I think this is not completely correct. I know that the cfapi is written from code-for-america as main object, but honestly, code-for-all shoul be a top level object as code-for-all has partners for all the individual countries who have brigades/chapters nationally. The hierarchy is therefor:

- Code For All
    - Country/Partner
        - Brigade/Chapter

For this to work; brigades should get a parent object being a partner (f.i. code-for-america, code-for-germany) it would then be possible to browse brigades per specific country.

Would it be possible to implement such a hierarchy?

**Comment by tdooner** [comment]
Hey @milovanderlinden, I'm curious if you saw the tags array that I added previously to the `brigade-information` repo? I think it could be used to implement a hierarchy like this, and also be more flexible for unforeseen structures.

For example, the "Brigade" tag indicates that the group is a brigade, and then there are tags for "Code for America" and "Code for Japan" as well. The API allows you to filter by tags so you could easily retrieve, say, a list of brigades tagged with "Official" and "Code for America". (That is what our [current brigade website](http://brigade.codeforamerica.org/) does.)

**Comment by milovanderlinden** [comment]
I could work from that, but it is not the most flexible solution. I would have to interpret all the free text and somehow relate them to organizations. It would be easier if I could be sure that a tag is an id to another organization.

**Comment by tdooner** [comment]
You can get all the OK Lab groups like this:
http://api.codeforamerica.org/api/organizations?tags[]=OK%20Lab

If you want all the top-level organizations, you can use the "Code for All" tag, which currently is only applied to the national (or continental) level organizations.

I'm not sure what you mean by "affiliate partners" -- do you have an example?

I know that this is unstructured, but I think we will have a problem if we try to impose too much hierarchy. For instance, consider Code for Africa. What do we do with them? Do we need to add another level so that Code for South Africa can be underneath them? There might also be regional brigades, for example some of us are talking about making a "Code for California" group. It gets messy very quickly.

**Comment by milovanderlinden** [comment]
It is not true that the "code for all tag" shows only national or continental partners. I am using the organizations.geojson on this page http://code-for-all.github.io/codeforall.org/partners/ and it shows for instance; Code For Mexico City, Hacking Monterrey, Code Namu, Code for Tomorrow and Open Brasil. It seems Code For All is currently used for anything not Code For America.

I am one of the folks "doing" Code For Europe. We have the same thing going as Code For Africa. I think the Code For All board would have to come up with an extra tag for instance for continental, regional, international and local. The policy (if I am correct) is that people interested in Code For All should be redirected to their national initiative and if not available; learn how to set one up. But I will bring this to the Code For All slack for discussion. Of course you can misuse tags for multidimensional relations, but I would like to try to at least have some convention accepted.

Governing partners: http://code-for-all.github.io/codeforall.org/partners/governing-partner
Affiliate partners: http://code-for-all.github.io/codeforall.org/partners/affiliate-partner

**Comment by milovanderlinden** [comment]
Let's close this issue for now. I don't want to mess up your development and I think this is more of an issue that needs to be solved by the Code For All board then a technical issue. Technically it is arbitrary. 
Thanks for thinking with me!

**Comment by tdooner** [comment]
Maybe a bit more of a convention around these tags would be helpful -- for instance by removing the "Code for All" tag from those brigades. Or, if they are affiliate partners, then by adding tags for "Affiliate Partner" and "Governing Partner".
